name = "JeCobblemon"
author = "WxAaRoNxW, JecoLambo"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0e3924cae0e7b7cc6535cbad9143a0801b187b193200bcd271c57d8dead69452"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
datapack-folder = "./global_packs/required_data"
