name = "JeCobblemon"
author = "WxAaRoNxW, JecoLambo"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5408966cf0d2819b8efbfcfdeebd144b15fc74d82aca13455567ccfb8e50fc37"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
datapack-folder = "./global_packs/required_data"
