name = "JeCobblemon"
author = "WxAaRoNxW, JecoLambo"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d2e2c222e5085a259d77d48a20c97c93112a9cc27aa09503d483f0a375f0940"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
datapack-folder = "./global_packs/required_data"
